In [2]:
import pandas as pd
import seaborn as sns
import matplotlib as plt
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df=pd.read_csv('datasets\student.csv')
df

Unnamed: 0    Id  Student_Age     Sex High_School_Type Scholarship  \
0             0  5001           21    Male            Other         50%   
1             1  5002           20    Male            Other         50%   
2             2  5003           21    Male            State         50%   
3             3  5004           18  Female          Private         50%   
4             4  5005           22    Male          Private         50%   
..          ...   ...          ...     ...              ...         ...   
140         140  5141           22  Female            State         50%   
141         141  5142           18  Female            State         75%   
142         142  5143           18  Female          Private         75%   
143         143  5144           22  Female            State         75%   
144         144  5145           18  Female          Private        100%   

    Additional_Work Sports_activity Transportation  Weekly_Study_Hours  \
0               Yes              No        Private                   0   
1               Yes              No        Private                   0   
2                No              No        Private                   2   
3               Yes              No            Bus                   2   
4                No              No            Bus                  12   
..              ...             ...            ...                 ...   
140             Yes             Yes        Private                   0   
141              No              No        Private                   0   
142              No              No        Private                   0   
143             Yes             Yes            Bus                  12   
144              No              No        Private                  12   

    Attendance Reading Notes Listening_in_Class Project_work Grade  
0       Always     Yes   Yes                 No           No    AA  
1       Always     Yes    No                Yes          Yes    AA  
2        Never      No    No                 No          Yes    AA  
3       Always      No   Yes                 No           No    AA  
4       Always     Yes    No                Yes          Yes    AA  
..         ...     ...   ...                ...          ...   ...  
140     Always      No   Yes                 No          Yes    CC  
141      Never      No   Yes                Yes           No    CC  
142     Always     Yes    No                 No           No    AA  
143  Sometimes      No   Yes                 No          Yes    CB  
144     Always     Yes    No                Yes           No    BB  

[145 rows x 16 columns]

In [4]:
df.shape

(145, 16)

In [5]:
df.isna().sum()

Unnamed: 0            0
Id                    0
Student_Age           0
Sex                   0
High_School_Type      0
Scholarship           1
Additional_Work       0
Sports_activity       0
Transportation        0
Weekly_Study_Hours    0
Attendance            0
Reading               0
Notes                 0
Listening_in_Class    0
Project_work          0
Grade                 0
dtype: int64

In [6]:
mode_value=df[df['Scholarship'].notna()]['Scholarship'].mode()[0]
mode_value

'50%'

In [7]:
df['scholarship']=df['Scholarship'].fillna(mode_value)


In [8]:
df.drop('Scholarship',axis=1,inplace=True)

In [9]:
df.isna().sum()

Unnamed: 0            0
Id                    0
Student_Age           0
Sex                   0
High_School_Type      0
Additional_Work       0
Sports_activity       0
Transportation        0
Weekly_Study_Hours    0
Attendance            0
Reading               0
Notes                 0
Listening_in_Class    0
Project_work          0
Grade                 0
scholarship           0
dtype: int64

In [10]:
df.duplicated().sum()

0

In [11]:
df.columns

Index(['Unnamed: 0', 'Id', 'Student_Age', 'Sex', 'High_School_Type',
       'Additional_Work', 'Sports_activity', 'Transportation',
       'Weekly_Study_Hours', 'Attendance', 'Reading', 'Notes',
       'Listening_in_Class', 'Project_work', 'Grade', 'scholarship'],
      dtype='object')

In [12]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [13]:
df.drop('Id',axis=1,inplace=True)

In [14]:
df.columns

Index(['Student_Age', 'Sex', 'High_School_Type', 'Additional_Work',
       'Sports_activity', 'Transportation', 'Weekly_Study_Hours', 'Attendance',
       'Reading', 'Notes', 'Listening_in_Class', 'Project_work', 'Grade',
       'scholarship'],
      dtype='object')

In [15]:
df['Sex'].unique()

array(['Male', 'Female'], dtype=object)

In [16]:
df['High_School_Type'].unique()

array(['Other', 'State', 'Private'], dtype=object)

In [17]:
df['Additional_Work'].unique()

array(['Yes', 'No'], dtype=object)

In [18]:
df['Sports_activity'].unique()

array(['No', 'Yes'], dtype=object)

In [19]:
df['Transportation'].unique()

array(['Private', 'Bus'], dtype=object)

In [20]:
df['Attendance'].value_counts()

Attendance
Always       98
Sometimes    25
Never        21
3             1
Name: count, dtype: int64

In [50]:
df['Attendance'].drop('3',inplace=True,axis=1)

ValueError: No axis named 1 for object type Series

In [21]:
df['Reading'].unique()


array(['Yes', 'No'], dtype=object)

In [22]:
df['Notes'].unique()

array(['Yes', 'No', '6'], dtype=object)

In [23]:
df['Listening_in_Class'].unique()

array(['No', 'Yes', '6'], dtype=object)

In [24]:
df['Project_work'].unique()

array(['No', 'Yes'], dtype=object)

In [25]:
df.columns


Index(['Student_Age', 'Sex', 'High_School_Type', 'Additional_Work',
       'Sports_activity', 'Transportation', 'Weekly_Study_Hours', 'Attendance',
       'Reading', 'Notes', 'Listening_in_Class', 'Project_work', 'Grade',
       'scholarship'],
      dtype='object')

In [26]:
cols=['High_School_Type','Attendance','Grade']
from sklearn.preprocessing import LabelEncoder
for col in df.select_dtypes(include=['object']).columns:
    le=LabelEncoder()
    df[col]=le.fit_transform(df[col])

In [27]:
df

Student_Age  Sex  High_School_Type  Additional_Work  Sports_activity  \
0             21    1                 0                1                0   
1             20    1                 0                1                0   
2             21    1                 2                0                0   
3             18    0                 1                1                0   
4             22    1                 1                0                0   
..           ...  ...               ...              ...              ...   
140           22    0                 2                1                1   
141           18    0                 2                0                0   
142           18    0                 1                0                0   
143           22    0                 2                1                1   
144           18    0                 1                0                0   

     Transportation  Weekly_Study_Hours  Attendance  Reading  Notes  \
0                 1                   0           1        1      2   
1                 1                   0           1        1      1   
2                 1                   2           2        0      1   
3                 0                   2           1        0      2   
4                 0                  12           1        1      1   
..              ...                 ...         ...      ...    ...   
140               1                   0           1        0      2   
141               1                   0           2        0      2   
142               1                   0           1        1      1   
143               0                  12           3        0      2   
144               1                  12           1        1      1   

     Listening_in_Class  Project_work  Grade  scholarship  
0                     1             0      0            2  
1                     2             1      0            2  
2                     1             1      0            2  
3                     1             0      0            2  
4                     2             1      0            2  
..                  ...           ...    ...          ...  
140                   1             1      4            2  
141                   2             0      4            3  
142                   1             0      0            3  
143                   1             1      3            3  
144                   2             0      2            0  

[145 rows x 14 columns]

In [28]:
x=df.drop('Project_work',axis=1)
y=df['Project_work']

In [29]:
x

Student_Age  Sex  High_School_Type  Additional_Work  Sports_activity  \
0             21    1                 0                1                0   
1             20    1                 0                1                0   
2             21    1                 2                0                0   
3             18    0                 1                1                0   
4             22    1                 1                0                0   
..           ...  ...               ...              ...              ...   
140           22    0                 2                1                1   
141           18    0                 2                0                0   
142           18    0                 1                0                0   
143           22    0                 2                1                1   
144           18    0                 1                0                0   

     Transportation  Weekly_Study_Hours  Attendance  Reading  Notes  \
0                 1                   0           1        1      2   
1                 1                   0           1        1      1   
2                 1                   2           2        0      1   
3                 0                   2           1        0      2   
4                 0                  12           1        1      1   
..              ...                 ...         ...      ...    ...   
140               1                   0           1        0      2   
141               1                   0           2        0      2   
142               1                   0           1        1      1   
143               0                  12           3        0      2   
144               1                  12           1        1      1   

     Listening_in_Class  Grade  scholarship  
0                     1      0            2  
1                     2      0            2  
2                     1      0            2  
3                     1      0            2  
4                     2      0            2  
..                  ...    ...          ...  
140                   1      4            2  
141                   2      4            3  
142                   1      0            3  
143                   1      3            3  
144                   2      2            0  

[145 rows x 13 columns]

In [30]:
y

0      0
1      1
2      1
3      0
4      1
      ..
140    1
141    0
142    0
143    1
144    0
Name: Project_work, Length: 145, dtype: int32

In [31]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [32]:
x_test.shape,x_train.shape

((44, 13), (101, 13))

In [33]:
#AdaBoosting classifier
from sklearn.ensemble import AdaBoostClassifier
abc=AdaBoostClassifier()
abc.fit(x_train,y_train)
y_pred=abc.predict(x_test)
y_pred

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0])

In [34]:
from sklearn.metrics import accuracy_score ,confusion_matrix,classification_report
accuracy_score(y_test,y_pred)

0.5227272727272727

In [35]:
confusion_matrix(y_test,y_pred)

array([[11, 14],
       [ 7, 12]], dtype=int64)

In [36]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.61      0.44      0.51        25
           1       0.46      0.63      0.53        19

    accuracy                           0.52        44
   macro avg       0.54      0.54      0.52        44
weighted avg       0.55      0.52      0.52        44



In [37]:
# Hyperparametre tuning for adaboosting 
from sklearn.model_selection import GridSearchCV
param_grid={'n_estimators':[50,100,200],'learning_rate':[0.01,0.1,1.0,1.5,2.0],'algorithm':['SAMME','SAMMER']}
grid_search=GridSearchCV(estimator=abc,param_grid=param_grid,cv=5,verbose=3)
grid_search.fit(x_train,y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits
[CV 1/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=50;, score=0.571 total time=   0.0s
[CV 2/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=50;, score=0.600 total time=   0.0s
[CV 3/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=50;, score=0.700 total time=   0.0s
[CV 4/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=50;, score=0.400 total time=   0.1s
[CV 5/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=50;, score=0.600 total time=   0.0s
[CV 1/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=100;, score=0.571 total time=   0.2s
[CV 2/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=100;, score=0.700 total time=   0.2s
[CV 3/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=100;, score=0.650 total time=   0.2s
[CV 4/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=100;, score=0.400 total time=   0.2s
[CV 5/5] END algorithm=SAMME, learning_rate

GridSearchCV(cv=5, estimator=AdaBoostClassifier(),
             param_grid={'algorithm': ['SAMME', 'SAMMER'],
                         'learning_rate': [0.01, 0.1, 1.0, 1.5, 2.0],
                         'n_estimators': [50, 100, 200]},
             verbose=3)

In [38]:
grid_search.best_params_

{'algorithm': 'SAMME', 'learning_rate': 0.1, 'n_estimators': 100}

In [39]:
best_model=grid_search.best_estimator_
y_pred_tuned=best_model.predict(x_test)
y_pred_tuned

array([0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0])

In [40]:
accuracy_score(y_test,y_pred_tuned)

0.7045454545454546

In [41]:
print(classification_report(y_test,y_pred_tuned))

              precision    recall  f1-score   support

           0       0.77      0.68      0.72        25
           1       0.64      0.74      0.68        19

    accuracy                           0.70        44
   macro avg       0.70      0.71      0.70        44
weighted avg       0.71      0.70      0.71        44



In [42]:
#Gradient Boosting classifier
from sklearn.ensemble import GradientBoostingClassifier
gbc=GradientBoostingClassifier()
gbc.fit(x_train,y_train)
y_pred=gbc.predict(x_test)
y_pred

array([0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [43]:
accuracy_score(y_test,y_pred)

0.5454545454545454

In [44]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.63      0.48      0.55        25
           1       0.48      0.63      0.55        19

    accuracy                           0.55        44
   macro avg       0.56      0.56      0.55        44
weighted avg       0.57      0.55      0.55        44



In [45]:
# Hyperparametre tuning for gradient boosting 
from sklearn.model_selection import GridSearchCV
param_grid={'n_estimators':[50,100,200],'learning_rate':[0.01,0.1,0.05,0.2]}
grid_search=GridSearchCV(estimator=gbc,param_grid=param_grid,cv=5,verbose=3)
grid_search.fit(x_train,y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5] END learning_rate=0.01, n_estimators=50;, score=0.619 total time=   0.0s
[CV 2/5] END learning_rate=0.01, n_estimators=50;, score=0.700 total time=   0.0s
[CV 3/5] END learning_rate=0.01, n_estimators=50;, score=0.650 total time=   0.0s
[CV 4/5] END learning_rate=0.01, n_estimators=50;, score=0.650 total time=   0.0s
[CV 5/5] END learning_rate=0.01, n_estimators=50;, score=0.500 total time=   0.0s
[CV 1/5] END learning_rate=0.01, n_estimators=100;, score=0.667 total time=   0.1s
[CV 2/5] END learning_rate=0.01, n_estimators=100;, score=0.700 total time=   0.1s
[CV 3/5] END learning_rate=0.01, n_estimators=100;, score=0.750 total time=   0.1s
[CV 4/5] END learning_rate=0.01, n_estimators=100;, score=0.550 total time=   0.1s
[CV 5/5] END learning_rate=0.01, n_estimators=100;, score=0.650 total time=   0.1s
[CV 1/5] END learning_rate=0.01, n_estimators=200;, score=0.571 total time=   0.3s
[CV 2/5] END learning_rate=0.01

GridSearchCV(cv=5, estimator=GradientBoostingClassifier(),
             param_grid={'learning_rate': [0.01, 0.1, 0.05, 0.2],
                         'n_estimators': [50, 100, 200]},
             verbose=3)

In [46]:
grid_search.best_params_

{'learning_rate': 0.01, 'n_estimators': 100}

In [47]:
best_model=grid_search.best_estimator_
y_pred_tuned=best_model.predict(x_test)
y_pred_tuned

array([0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [48]:
accuracy_score(y_test,y_pred_tuned)

0.6136363636363636

In [49]:
print(classification_report(y_test,y_pred_tuned))

              precision    recall  f1-score   support

           0       0.68      0.60      0.64        25
           1       0.55      0.63      0.59        19

    accuracy                           0.61        44
   macro avg       0.61      0.62      0.61        44
weighted avg       0.62      0.61      0.62        44

