In [51]:
import pandas as pd
import seaborn as sns
import matplotlib as plt
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df=pd.read_csv('datasets\StressLevelDataset.csv')
df

anxiety_level  self_esteem  mental_health_history  depression  headache  \
0                14           20                      0          11         2   
1                15            8                      1          15         5   
2                12           18                      1          14         2   
3                16           12                      1          15         4   
4                16           28                      0           7         2   
...             ...          ...                    ...         ...       ...   
1095             11           17                      0          14         3   
1096              9           12                      0           8         0   
1097              4           26                      0           3         1   
1098             21            0                      1          19         5   
1099             18            6                      1          15         3   

      blood_pressure  sleep_quality  breathing_problem  noise_level  \
0                  1              2                  4            2   
1                  3              1                  4            3   
2                  1              2                  2            2   
3                  3              1                  3            4   
4                  3              5                  1            3   
...              ...            ...                ...          ...   
1095               1              3                  2            2   
1096               3              0                  0            0   
1097               2              5                  2            2   
1098               3              1                  4            3   
1099               3              0                  3            3   

      living_conditions  ...  basic_needs  academic_performance  study_load  \
0                     3  ...            2                     3           2   
1                     1  ...            2                     1           4   
2                     2  ...            2                     2           3   
3                     2  ...            2                     2           4   
4                     2  ...            3                     4           3   
...                 ...  ...          ...                   ...         ...   
1095                  2  ...            3                     2           2   
1096                  1  ...            4                     0           1   
1097                  3  ...            4                     5           1   
1098                  1  ...            1                     2           5   
1099                  0  ...            3                     3           4   

      teacher_student_relationship  future_career_concerns  social_support  \
0                                3                       3               2   
1                                1                       5               1   
2                                3                       2               2   
3                                1                       4               1   
4                                1                       2               1   
...                            ...                     ...             ...   
1095                             2                       3               3   
1096                             1                       1               1   
1097                             4                       1               3   
1098                             1                       4               1   
1099                             3                       3               1   

      peer_pressure  extracurricular_activities  bullying  stress_level  
0                 3                           3         2             1  
1                 4                           5         5             2  
2                 3                           2         2             1 

In [53]:
df.head()

anxiety_level  self_esteem  mental_health_history  depression  headache  \
0             14           20                      0          11         2   
1             15            8                      1          15         5   
2             12           18                      1          14         2   
3             16           12                      1          15         4   
4             16           28                      0           7         2   

   blood_pressure  sleep_quality  breathing_problem  noise_level  \
0               1              2                  4            2   
1               3              1                  4            3   
2               1              2                  2            2   
3               3              1                  3            4   
4               3              5                  1            3   

   living_conditions  ...  basic_needs  academic_performance  study_load  \
0                  3  ...            2                     3           2   
1                  1  ...            2                     1           4   
2                  2  ...            2                     2           3   
3                  2  ...            2                     2           4   
4                  2  ...            3                     4           3   

   teacher_student_relationship  future_career_concerns  social_support  \
0                             3                       3               2   
1                             1                       5               1   
2                             3                       2               2   
3                             1                       4               1   
4                             1                       2               1   

   peer_pressure  extracurricular_activities  bullying  stress_level  
0              3                           3         2             1  
1              4                           5         5             2  
2              3                           2         2             1  
3              4                           4         5             2  
4              5                           0         5             1  

[5 rows x 21 columns]

In [54]:
df.columns

Index(['anxiety_level', 'self_esteem', 'mental_health_history', 'depression',
       'headache', 'blood_pressure', 'sleep_quality', 'breathing_problem',
       'noise_level', 'living_conditions', 'safety', 'basic_needs',
       'academic_performance', 'study_load', 'teacher_student_relationship',
       'future_career_concerns', 'social_support', 'peer_pressure',
       'extracurricular_activities', 'bullying', 'stress_level'],
      dtype='object')

In [55]:
cols=['anxiety_level', 'self_esteem', 'mental_health_history', 'depression',
       'headache', 'blood_pressure', 'sleep_quality', 'breathing_problem',
       'noise_level', 'living_conditions', 'safety', 'basic_needs',
       'academic_performance', 'study_load', 'teacher_student_relationship',
       'future_career_concerns', 'social_support', 'peer_pressure',
       'extracurricular_activities', 'bullying', 'stress_level']

In [56]:
for col in cols:
    print(df[col].unique())

[14 15 12 16 20  4 17 13  6  5  9  2 11  7 21  3 18  0  8  1 19 10]
[20  8 18 12 28 13 26  3 22 15 23 21 25  1 27  5  6  9 29 30  4 19 16  2
  0 14  7 17 24 11 10]
[0 1]
[11 15 14  7 21  6 22 12 27 25  8 24  3  1  0  5 26 20 10  9  2 16  4 13
 18 23 17 19]
[2 5 4 3 1 0]
[1 3 2]
[2 1 5 4 3 0]
[4 2 3 1 5 0]
[2 3 4 1 0 5]
[3 1 2 4 5 0]
[3 2 4 1 5 0]
[2 3 1 4 5 0]
[3 1 2 4 5 0]
[2 4 3 5 1 0]
[3 1 2 4 5 0]
[3 5 2 4 1 0]
[2 1 3 0]
[3 4 5 2 1 0]
[3 5 2 4 0 1]
[2 5 1 4 3 0]
[1 2 0]


In [57]:
x=df.drop('mental_health_history',axis=1)
y=df['mental_health_history']
x

anxiety_level  self_esteem  depression  headache  blood_pressure  \
0                14           20          11         2               1   
1                15            8          15         5               3   
2                12           18          14         2               1   
3                16           12          15         4               3   
4                16           28           7         2               3   
...             ...          ...         ...       ...             ...   
1095             11           17          14         3               1   
1096              9           12           8         0               3   
1097              4           26           3         1               2   
1098             21            0          19         5               3   
1099             18            6          15         3               3   

      sleep_quality  breathing_problem  noise_level  living_conditions  \
0                 2                  4            2                  3   
1                 1                  4            3                  1   
2                 2                  2            2                  2   
3                 1                  3            4                  2   
4                 5                  1            3                  2   
...             ...                ...          ...                ...   
1095              3                  2            2                  2   
1096              0                  0            0                  1   
1097              5                  2            2                  3   
1098              1                  4            3                  1   
1099              0                  3            3                  0   

      safety  basic_needs  academic_performance  study_load  \
0          3            2                     3           2   
1          2            2                     1           4   
2          3            2                     2           3   
3          2            2                     2           4   
4          4            3                     4           3   
...      ...          ...                   ...         ...   
1095       2            3                     2           2   
1096       3            4                     0           1   
1097       4            4                     5           1   
1098       1            1                     2           5   
1099       4            3                     3           4   

      teacher_student_relationship  future_career_concerns  social_support  \
0                                3                       3               2   
1                                1                       5               1   
2                                3                       2               2   
3                                1                       4               1   
4                                1                       2               1   
...                            ...                     ...             ...   
1095                             2                       3               3   
1096                             1                       1               1   
1097                             4                       1               3   
1098                             1                       4               1   
1099                             3                       3               1   

      peer_pressure  extracurricular_activities  bullying  stress_level  
0                 3                           3         2             1  
1                 4                           5         5             2  
2                 3                           2         2             1  
3                 4                           4         5             2  
4                 5                           0         5             1  
...             ...                         ...       ...           ...  
1095            

In [58]:
y

0       0
1       1
2       1
3       1
4       0
       ..
1095    0
1096    0
1097    0
1098    1
1099    1
Name: mental_health_history, Length: 1100, dtype: int64

In [59]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [60]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [61]:
from sklearn.decomposition import PCA
pca=PCA(n_components=5)
x_train=pca.fit_transform(x_train)
x_test=pca.transform(x_test)

In [62]:
x_train.shape,x_test.shape

((770, 5), (330, 5))

In [63]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

In [64]:
p1=Pipeline([('lgc',LogisticRegression())])
p2=Pipeline([('dtc',DecisionTreeClassifier())])
p3=Pipeline([('svc',SVC())])
p4=Pipeline([('rfc',RandomForestClassifier())])

In [65]:
pipelines=[p1,p2,p3,p4]
for pipe in pipelines:
    pipe.fit(x_train,y_train)
    y_pred=pipe.predict(x_test)
    print(accuracy_score(y_test,y_pred))

0.7757575757575758
0.7393939393939394


0.7727272727272727
0.7727272727272727


In [66]:
rfc=RandomForestClassifier()
rfc

RandomForestClassifier()

In [67]:
from sklearn.model_selection import GridSearchCV
param_grid={'max_depth':[1,50,100,150,200],'n_estimators':[50,100,200,300],'criterion':['gini','entropy']}
grid_search=GridSearchCV(rfc,param_grid=param_grid,cv=5,verbose=3)
grid_search.fit(x_train,y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits
[CV 1/5] END criterion=gini, max_depth=1, n_estimators=50;, score=0.818 total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=1, n_estimators=50;, score=0.818 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=1, n_estimators=50;, score=0.766 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=1, n_estimators=50;, score=0.760 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=1, n_estimators=50;, score=0.753 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=1, n_estimators=100;, score=0.812 total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=1, n_estimators=100;, score=0.818 total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=1, n_estimators=100;, score=0.773 total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=1, n_estimators=100;, score=0.760 total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=1, n_estimators=100;, score=0.760 total time=   0.2s
[CV 1/5] END criterion=

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 50, 100, 150, 200],
                         'n_estimators': [50, 100, 200, 300]},
             verbose=3)

In [68]:
grid_search.best_params_

{'criterion': 'gini', 'max_depth': 1, 'n_estimators': 100}

In [69]:
best_model=grid_search.best_estimator_
best_model

RandomForestClassifier(max_depth=1)

In [70]:
y_pred_tuned=best_model.predict(x_test)
y_pred_tuned

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,

In [71]:
accuracy_score(y_test,y_pred_tuned)

0.7787878787878788