In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("Hepatitis C virus.csv")

In [3]:
df.shape

(615, 14)

In [4]:
df.head()

Unnamed: 0       Category  Age Sex   ALB   ALP   ALT   AST   BIL    CHE  \
0           1  0=Blood Donor   32   m  38.5  52.5   7.7  22.1   7.5   6.93   
1           2  0=Blood Donor   32   m  38.5  70.3  18.0  24.7   3.9  11.17   
2           3  0=Blood Donor   32   m  46.9  74.7  36.2  52.6   6.1   8.84   
3           4  0=Blood Donor   32   m  43.2  52.0  30.6  22.6  18.9   7.33   
4           5  0=Blood Donor   32   m  39.2  74.1  32.6  24.8   9.6   9.15   

   CHOL   CREA   GGT  PROT  
0  3.23  106.0  12.1  69.0  
1  4.80   74.0  15.6  76.5  
2  5.20   86.0  33.2  79.3  
3  4.74   80.0  33.8  75.7  
4  4.32   76.0  29.9  68.7

In [5]:
df.drop("Unnamed: 0", axis=1, inplace=True)

In [6]:
df.isna().sum()

Category     0
Age          0
Sex          0
ALB          1
ALP         18
ALT          1
AST          0
BIL          0
CHE          0
CHOL        10
CREA         0
GGT          0
PROT         1
dtype: int64

In [7]:
df.duplicated().sum()

0

In [8]:
df.dropna(inplace=True)

In [9]:
df.shape

(589, 13)

In [10]:
df['Category'].value_counts()

Category
0=Blood Donor             526
3=Cirrhosis                24
1=Hepatitis                20
2=Fibrosis                 12
0s=suspect Blood Donor      7
Name: count, dtype: int64

In [11]:
df['Category'] = df['Category'].map({'0=Blood Donor':0, '0s=suspect Blood Donor':1, '1=Hepatitis':2, '2=Fibrosis':3, '3=Cirrhosis':4})

In [12]:
df['Sex'] = df['Sex'].map({'m':0, 'f':1})

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 589 entries, 0 to 612
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Category  589 non-null    int64  
 1   Age       589 non-null    int64  
 2   Sex       589 non-null    int64  
 3   ALB       589 non-null    float64
 4   ALP       589 non-null    float64
 5   ALT       589 non-null    float64
 6   AST       589 non-null    float64
 7   BIL       589 non-null    float64
 8   CHE       589 non-null    float64
 9   CHOL      589 non-null    float64
 10  CREA      589 non-null    float64
 11  GGT       589 non-null    float64
 12  PROT      589 non-null    float64
dtypes: float64(10), int64(3)
memory usage: 64.4 KB


In [14]:
X = df.drop('Category', axis=1)
y = df['Category']

In [15]:
X

Age  Sex   ALB    ALP   ALT    AST   BIL    CHE  CHOL   CREA    GGT  PROT
0     32    0  38.5   52.5   7.7   22.1   7.5   6.93  3.23  106.0   12.1  69.0
1     32    0  38.5   70.3  18.0   24.7   3.9  11.17  4.80   74.0   15.6  76.5
2     32    0  46.9   74.7  36.2   52.6   6.1   8.84  5.20   86.0   33.2  79.3
3     32    0  43.2   52.0  30.6   22.6  18.9   7.33  4.74   80.0   33.8  75.7
4     32    0  39.2   74.1  32.6   24.8   9.6   9.15  4.32   76.0   29.9  68.7
..   ...  ...   ...    ...   ...    ...   ...    ...   ...    ...    ...   ...
608   58    1  34.0   46.4  15.0  150.0   8.0   6.26  3.98   56.0   49.7  80.6
609   59    1  39.0   51.3  19.6  285.8  40.0   5.77  4.51  136.1  101.1  70.5
610   62    1  32.0  416.6   5.9  110.3  50.0   5.57  6.30   55.7  650.9  68.5
611   64    1  24.0  102.8   2.9   44.4  20.0   1.54  3.02   63.0   35.9  71.3
612   64    1  29.0   87.3   3.5   99.0  48.0   1.66  3.63   66.7   64.2  82.0

[589 rows x 12 columns]

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=66)

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
model = RandomForestClassifier()

In [19]:
model.fit(X_train, y_train)

RandomForestClassifier()

In [20]:
y_pred = model.predict(X_test)

In [21]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [22]:
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9830508474576272
[[54  0  0  0  0]
 [ 0  2  0  0  0]
 [ 0  0  0  1  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  2]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        54
           1       1.00      1.00      1.00         2
           2       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         0
           4       1.00      1.00      1.00         2

    accuracy                           0.98        59
   macro avg       0.60      0.60      0.60        59
weighted avg       0.98      0.98      0.98        59



In [28]:
param_grid = {
    'n_estimators': [100, 200, 300, 500],
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 5, 10]
    }

In [29]:
from sklearn.model_selection import GridSearchCV

In [30]:
grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2)

In [31]:
grid.fit(X_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits


GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 5, 10],
                         'n_estimators': [100, 200, 300, 500]},
             verbose=2)

In [32]:
grid.best_params_

{'criterion': 'entropy', 'max_depth': None, 'n_estimators': 100}

In [33]:
grid.best_score_

0.9509433962264151

In [34]:
y_pred_grid = grid.predict(X_test)

In [36]:
print(accuracy_score(y_test, y_pred_grid))

0.9322033898305084
